[package]
name = "kr580compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
lalrpop-util = { version = "0.19.6", features = ["lexer"]}
clap = "3.0.0-beta.5"

[build-dependencies]
lalrpop = "0.19.6"